version: "3.3"
services:

  db_1:
    image: mysql/mysql-server:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'CCLoanLaptops'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    
    build: ./app
    links:
      - db_1
    ports:
      - "5000:5000"



